- name: Deploy Payflow Application
  hosts: dfs,dfs_new
  become: true
  vars_files:
    - "roles/payflow/vars/payflow-{{ environment }}.yml"
    - "roles/payflow/vars/payflow-secrets-{{ environment }}.yml"

  roles:
    - { role: payflow, tags: [ 'payflow' ] }
