name: Release Automation

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.set-tag.outputs.tag_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
  
      - name: Create Tag
        id: set-tag
        run: |
          TAG_NAME="payflow-release-0.0.2"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
  
          # Output the tag name for use in subsequent jobs using environment files
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "::set-output name=tag_name::$TAG_NAME"

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Git
        run: |
          git fetch --tags

      - name: Use the Tag Name
        run: |
          TAG_NAME="${{ needs.create-release-tag.outputs.tag_name }}"
          git fetch --tags --force
          git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)  # Sync local repo with the remote branch
  
          # Use the tag name in your script
          echo "Processing tag $TAG_NAME"
        env:
          TAG_NAME: ${{ needs.create-release-tag.outputs.tag_name }}

      - name: Use the Tag Name 2
        run: |
          echo "The tag name is: $TAG_NAME"
          git fetch --tags --force
          git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)  # Sync local repo with the remote branch
  
          # Use the tag name in your script
          echo "Processing tag $TAG_NAME"
        env:
          TAG_NAME: ${{ env.TAG_NAME }}

