name: Debug Runner

on: workflow_dispatch

jobs:
  connectivity-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test GitHub API Connectivity
        run: |
          curl -v https://api.github.com/repos/peter-evans/create-issue
