name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1
        with:
         fetch-depth: 0
      - name: Setup Java 21
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'maven'
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.10.0
        with:
          java-version: 21
          maven-version: 3.9.5
      - name: Cache maven
        uses: actions/cache@v3
        with:
         path: |
           '~/.m2'
         key: ${{ runner.os}}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os}}-m2-

      - name: Test
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B clean verify sonar:sonar

  build-and-deploy-docker:
    runs-on: ubuntu-latest

    needs: [build-and-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_LOWER/testdemo:${{ github.sha }} .
          docker push ghcr.io/$REPO_LOWER/testdemo:${{ github.sha }}