name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      environment_type:
        description: 'Select environment to deploy to'
        required: true
        default: 'dev'
        type: string
        options:
          - dev
          - staging
          - prod

jobs:
  notify:
    if: ${{ github.event.inputs.environment_type == 'prod' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification to Approvers
        uses: slackapi/slack-github-action@v1.22.0
        with:
          slack-message: |
            🚨 *Approval Needed:* Deployment to production is waiting for approval. Please review and approve it in GitHub.
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: notify
    if: ${{ github.event.inputs.environment_type == 'prod' }}
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
        env:
          DEPLOY_ENV: prod
