name: Scheduled tests

on:
  schedule:
     - cron: '*/2 * * * *'

jobs:
  trigger-dev-tests:
    runs-on: ubuntu-latest
    env:
      RUN_DEV_TESTS: false
    if: ${{ env.RUN_DEV_TESTS != 'false' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Add other steps as needed

      - name: Checkout repository
        run: echo "Dev run"
      
  trigger-INT-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Add other steps as needed

      - name: Checkout repository
        run: echo "Dev run"
