name: Create Release Tag

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (e.g., v1.0.0)"
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for tagging

      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "payflow-release-${{ github.event.inputs.release_version }}"
          git push origin "payflow-release-${{ github.event.inputs.release_version }}"
      
