name: Deploy Payflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, prod)'
        required: true
        default: dev
      target:
        description: 'Target hosts to deploy (e.g., dfs1-dev)'
        required: true
        default: dfs1-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Deploy Payflow
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PWD_DEV }}
      run: |
        ansible-playbook -vvv -i inventory.ini \
          -e "environment=${{ inputs.environment }}" \
          -l ${{ inputs.target }} \
          --vault-password-file /dev/stdin <<< "$ANSIBLE_VAULT_PASSWORD" \
          -t payflow \
          -e "@roles/payflow/vars/payflow-${{ inputs.environment }}.yml" \
          -e "@roles/payflow/vars/payflow-secrets-${{ inputs.environment }}.yml" \
          -e "ansible_become_pass=$ANSIBLE_VAULT_PASSWORD"

    - name: Show Deployed File Content
      run: cat /appdir/payflow/payflow.conf
