name: Prod Payflow Deployment

on:
  workflow_dispatch:
    inputs:
      environment_type:
        description: 'Select the type of environment'
        required: true
        type: choice
        options:
          - development
          - sandbox
          - production

      development_environment:
        description: 'Select the development environment'
        required: false
        type: choice
        options:
          - ""
          - Dev_server_dfs1_dev
          - Dev_server_dfs2_dev

      sandbox_environment:
        description: 'Select the sandbox environment'
        required: false
        type: choice
        options:
          - ""
          - UK_sandbox_001_crx_t_dfs_l
          - UK_sandbox_001_chn_t_dfs_l

      prod_environment:
        description: 'Select the production environment'
        required: false
        type: choice
        options:
          - ""
          - UK_prod_001_crx_p_dfs_l
          - UK_prod_001_chn_p_dfs_l

env:
  JAVA_VERSION: 21
  MAVEN_VERSION: 3.9.5

jobs:
  application-deployment:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Send Slack Notification Before Approval
        run: echo "Slack notification sent."
        

      - name: Request Approval
        run: echo "Waiting for manual approval through GitHub environment."

      - name: Approve Deployment
        uses: actions/github-script@v6
        with:
          script: |
            const { github, context } = require('@actions/github');
      
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'manual-payflow-deployment.yml',
              ref: 'main', // Specify the branch
              inputs: {
                environment_type: 'prod',
                approved: 'true'
              }
            });



      # Step 1: Validate Inputs
      - name: Validate Inputs
        run: |
          if [[ "${{ github.event.inputs.environment_type }}" == "prod" ]]; then
            if [[ -z "${{ github.event.inputs.prod_environment }}" ]]; then
              echo "Error: You must select a production environment."
              exit 1
            fi
            echo "TARGET_ENVIRONMENT=${{ github.event.inputs.prod_environment }}" >> $GITHUB_ENV
          else
            echo "Non-prod deployment detected. Proceeding without approval."
            exit 0
          fi
      

      # Step 4: Proceed After Approval
      - name: Continue Deployment
        if: success()
        run: echo "Approval received. Proceeding with deployment."

      # Add additional deployment steps below
      - name: Deploy Application
        run: echo "Deploying application to ${{ env.TARGET_ENVIRONMENT }}..."
